builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: lucagrulla
    name: homebrew-cw
  commit_author:
    name: lucagrulla
    email:
  folder: Formula
  homepage: "https://www.lucagrulla.com/cw"
  description: "The best way to tail AWS Cloudwatch Logs from your terminal"
  caveats: "In order to get cw completion,
        [bash] you need to install `bash-completion` with brew.
        OR
        [zsh], add the following line to your ~/.zshrc:
          source #{HOMEBREW_PREFIX}/share/zsh/site-functions/cw"
  install: |
    bin.install "cw"

    system bin/"cw --completion-script-bash > cw.bash"
    bash_completion.install "cw.bash"

    system bin/"cw --help-man > cw.1"
    man1.install "cw.1"


    # system bin/"cw completion zsh > cw.zsh"
    # zsh_completion.install "cw.zsh"
scoop:
  bucket:
    owner: lucagrulla
    name: cw-scoop-bucket
  homepage: "https://www.lucagrulla.com/cw"
  commit_author:
    name: lucagrulla
    email:
  description: "The best way to tail AWS Cloudwatch Logs from your terminal"
  license: Apache-2.0
  persist:
    - "data"
    - "config.toml"