name: cw
version: git
summary: An interactive web server.
description: |
  The best way to tail AWS Cloudwatch Logs from your terminal.

grade: devel
confinement: devmode

parts:
  cw:
    source: .
    plugin: go
    go-importpath: github.com/gchaincl/httplab

apps:
  cw:
    command: cw